// Build config actions
export const CONFIG_BUILD_ADD_BUILD_VAR = 'CONFIG_BUILD_ADD_BUILD_VAR';
export const CONFIG_BUILD_ON_BUILD_VAR_DELETE =
  'CONFIG_BUILD_ON_BUILD_VAR_DELETE';
export const CONFIG_BUILD_UPDATE_BY_PROP = 'CONFIG_BUILD_UPDATE_BY_PROP';
export const CONFIG_BUILD_ON_BUILD_CAPS_DELETE =
  'CONFIG_BUILD_ON_BUILD_CAPS_DELETE';
export const CONFIG_BUILD_UPDATE_SELECTED_VERSIONS =
  'CONFIG_BUILD_UPDATE_SELECTED_VERSIONS';
export const CONFIG_BUILD_ON_VERSIONS_DELETE =
  'CONFIG_BUILD_ON_VERSIONS_DELETE';

// Build actions
export const BUILD_UPDATE_BY_PROP = 'BUILD_UPDATE_BY_PROP';
export const BUILD_START_RUN = 'BUILD_START_RUN';
export const BUILD_CANCEL_RUN = 'BUILD_CANCEL_RUN';
export const BUILD_COMPLETE_RUN = 'BUILD_COMPLETE_RUN';
export const BUILD_NEW_RUN = 'BUILD_NEW_RUN';
export const BUILD_NEW_SESSION_SUCCESS = 'BUILD_NEW_SESSION_SUCCESS';
export const BUILD_NEW_SESSION_ERROR = 'BUILD_NEW_SESSION_ERROR';
