// Build config actions
export const CONFIG_BUILD_ADD_BUILD_VAR = 'CONFIG_BUILD_ADD_BUILD_VAR';
export const CONFIG_BUILD_UPDATE_OS = 'CONFIG_BUILD_UPDATE_OS';
export const CONFIG_BUILD_UPDATE_BROWSER = 'CONFIG_BUILD_UPDATE_BROWSER';
export const CONFIG_BUILD_UPDATE_SELECTED_VERSIONS =
  'CONFIG_BUILD_UPDATE_SELECTED_VERSIONS';
