export const RESET_STATE_ON_ERROR = 'RESET_STATE_ON_ERROR';
export const BATCH_ACTIONS = 'BATCH_ACTIONS';
export const SET_FILES = 'SET_FILES';
export const SET_PROJECT = 'SET_PROJECT';
export const SET_VERSION_LAST_RUN = 'SET_VERSION_LAST_RUN';
export const PUSH_COMPLETED_BUILDS = 'PUSH_COMPLETED_BUILDS';

// Explorer actions
export const EXP_LOAD_FILES = 'EXP_LOAD_FILES';
export const EXP_UNLOAD_FILE = 'EXP_UNLOAD_FILE';
export const EXP_NEW_ITEM = 'EXP_NEW_ITEM';
export const EXP_RENAME_ITEM = 'EXP_RENAME_ITEM';
export const EXP_DELETE_ITEM = 'EXP_DELETE_ITEM';
export const EXP_DELETE_REVERT = 'EXP_DELETE_REVERT';

// Editor actions
export const EDR_EXP_VERSIONS_DELETED = 'EDR_EXP_VERSIONS_DELETED';
export const EDR_EXP_VERSION_CLICK = 'EDR_EXP_VERSION_CLICK';
export const EDR_EXP_VERSION_DBL_CLICK = 'EDR_EXP_VERSION_DBL_CLICK';
export const EDR_SWITCH_TAB = 'EDR_SWITCH_TAB';
export const EDR_CLOSE_TAB = 'EDR_CLOSE_TAB';
export const EDR_DBL_CLICK_TAB = 'EDR_DBL_CLICK_TAB';
export const EDR_VERSION_CODE_UPDATED = 'EDR_VERSION_CODE_UPDATED';

// Dry Run config actions
export const CONFIG_DRY_ADD_BUILD_VAR = 'CONFIG_DRY_ADD_BUILD_VAR';
export const CONFIG_DRY_ON_BUILD_VAR_DELETE = 'CONFIG_DRY_ON_BUILD_VAR_DELETE';
export const CONFIG_DRY_UPDATE_BROWSER = 'CONFIG_DRY_UPDATE_BROWSER';
export const CONFIG_DRY_UPDATE_PLATFORM = 'CONFIG_DRY_UPDATE_PLATFORM';

// Variable actions
export const VAR_SET = 'VAR_SET';
export const VAR_DELETE = 'VAR_DELETE';
export const VAR_NEW = 'VAR_NEW';
export const VAR_EDIT = 'VAR_EDIT';

// Build Run actions
export const RUN_BUILD_ON_NEW_RUN = 'RUN_BUILD_ON_NEW_RUN';
export const RUN_BUILD_UPDATE_BY_PROP = 'RUN_BUILD_UPDATE_BY_PROP';
export const RUN_BUILD_ON_COMPLETED = 'RUN_BUILD_ON_COMPLETED';
export const RUN_BUILD_COMPLETE_ON_ERROR = 'RUN_BUILD_COMPLETE_ON_ERROR';
export const RUN_BUILD_UPDATE_VERSION = 'RUN_BUILD_UPDATE_VERSION';
