export const RESET_STATE_ON_ERROR = 'RESET_STATE_ON_ERROR';
export const BATCH_ACTIONS = 'BATCH_ACTIONS';
export const SET_FILES = 'SET_FILES';
export const SET_PROJECT = 'SET_PROJECT';
export const SET_VERSION_LAST_RUN = 'VERSION_LAST_RUN';

// Explorer actions
export const EXP_LOAD_FILES = 'EXP_LOAD_FILES';
export const EXP_UNLOAD_FILE = 'EXP_UNLOAD_FILE';
export const EXP_NEW_ITEM = 'EXP_NEW_ITEM';
export const EXP_RENAME_ITEM = 'EXP_RENAME_ITEM';
export const EXP_DELETE_ITEM = 'EXP_DELETE_ITEM';
export const EXP_DELETE_REVERT = 'EXP_DELETE_REVERT';

// Editor actions
export const EDR_EXP_VERSIONS_DELETED = 'EDR_EXP_VERSIONS_DELETED';
export const EDR_EXP_VERSION_CLICK = 'EDR_EXP_VERSION_CLICK';
export const EDR_EXP_VERSION_DBL_CLICK = 'EDR_EXP_VERSION_DBL_CLICK';
export const EDR_SWITCH_TAB = 'EDR_SWITCH_TAB';
export const EDR_CLOSE_TAB = 'EDR_CLOSE_TAB';
export const EDR_DBL_CLICK_TAB = 'EDR_DBL_CLICK_TAB';
export const EDR_VERSION_CODE_UPDATED = 'EDR_VERSION_CODE_UPDATED';

// Build actions
export const RUN_BUILD = 'RUN_BUILD';
