export const RESET_STATE = 'RESET_STATE';
export const BATCH_ACTIONS = 'BATCH_ACTIONS';
export const SET_FILES = 'SET_FILES';
export const SET_PROJECT = 'SET_PROJECT';
export const SET_VERSION_LAST_RUN = 'SET_VERSION_LAST_RUN';
export const CLEAR_VERSION_LAST_RUN_BY_RUN_TYPE =
  'CLEAR_VERSION_LAST_RUN_BY_RUN_TYPE';
export const CLEAR_VERSIONS_LAST_RUN = 'CLEAR_VERSIONS_LAST_RUN';
export const PUSH_COMPLETED_BUILDS = 'PUSH_COMPLETED_BUILDS';
export const VERSION_CODE_SAVE_IN_PROGRESS = 'VERSION_CODE_SAVE_IN_PROGRESS';
export const VERSION_CODE_SAVE_COMPLETED = 'VERSION_CODE_SAVE_COMPLETED';

// Explorer actions
export const EXP_LOAD_FILES = 'EXP_LOAD_FILES';
export const EXP_UNLOAD_FILE = 'EXP_UNLOAD_FILE';
export const EXP_NEW_ITEM = 'EXP_NEW_ITEM';
export const EXP_RENAME_ITEM = 'EXP_RENAME_ITEM';
export const EXP_DELETE_ITEM = 'EXP_DELETE_ITEM';
export const EXP_DELETE_REVERT = 'EXP_DELETE_REVERT';

// Editor actions
export const EDR_EXP_VERSIONS_DELETED = 'EDR_EXP_VERSIONS_DELETED';
export const EDR_EXP_VERSION_CLICK = 'EDR_EXP_VERSION_CLICK';
export const EDR_EXP_VERSION_DBL_CLICK = 'EDR_EXP_VERSION_DBL_CLICK';
export const EDR_SWITCH_TAB = 'EDR_SWITCH_TAB';
export const EDR_CLOSE_TAB = 'EDR_CLOSE_TAB';
export const EDR_DBL_CLICK_TAB = 'EDR_DBL_CLICK_TAB';
export const EDR_VERSION_CODE_UPDATED = 'EDR_VERSION_CODE_UPDATED';

// Dry Run config actions
export const CONFIG_DRY_ADD_BUILD_VAR = 'CONFIG_DRY_ADD_BUILD_VAR';
export const CONFIG_DRY_ON_BUILD_VAR_DELETE = 'CONFIG_DRY_ON_BUILD_VAR_DELETE';
export const CONFIG_DRY_UPDATE_BROWSER = 'CONFIG_DRY_UPDATE_BROWSER';
export const CONFIG_DRY_UPDATE_PLATFORM = 'CONFIG_DRY_UPDATE_PLATFORM';

// Variable actions
export const VAR_SET = 'VAR_SET';
export const VAR_DELETE = 'VAR_DELETE';
export const VAR_NEW = 'VAR_NEW';
export const VAR_EDIT = 'VAR_EDIT';

// Build Run actions
export const RUN_BUILD_ON_NEW_RUN = 'RUN_BUILD_ON_NEW_RUN';
export const RUN_BUILD_UPDATE_BY_PROP = 'RUN_BUILD_UPDATE_BY_PROP';
export const RUN_BUILD_ON_COMPLETED = 'RUN_BUILD_ON_COMPLETED';
export const RUN_BUILD_COMPLETE_ON_ERROR = 'RUN_BUILD_COMPLETE_ON_ERROR';
export const RUN_BUILD_UPDATE_VERSION = 'RUN_BUILD_UPDATE_VERSION';

// Dry Run actions
export const RUN_DRY_ON_NEW_RUN = 'RUN_DRY_ON_NEW_RUN';
export const RUN_DRY_UPDATE_BY_PROP = 'RUN_DRY_UPDATE_BY_PROP';
export const RUN_DRY_ON_COMPLETED = 'RUN_DRY_ON_COMPLETED';
export const RUN_DRY_COMPLETE_ON_ERROR = 'RUN_DRY_COMPLETE_ON_ERROR';
export const RUN_DRY_UPDATE_VERSION = 'RUN_DRY_UPDATE_VERSION';
export const RUN_DRY_RESET_VERSION = 'RUN_DRY_RESET_VERSION';
export const RUN_DRY_MARK_VERSION_STATUS = 'RUN_DRY_MARK_VERSION_STATUS';

// Dry actions
export const DRY_UPDATE_BY_PROP = 'DRY_UPDATE_BY_PROP';
export const DRY_START_RUN = 'DRY_START_RUN';
export const DRY_COMPLETE_RUN = 'DRY_COMPLETE_RUN';

// Parse actions
export const PARSE_START_RUN = 'PARSE_START_RUN';
export const PARSE_COMPLETE_RUN = 'PARSE_COMPLETE_RUN';

// Parse Run actions
export const RUN_PARSE_ON_NEW_RUN = 'RUN_PARSE_ON_NEW_RUN';
export const RUN_PARSE_ON_COMPLETED = 'RUN_PARSE_ON_COMPLETED';
export const RUN_PARSE_COMPLETE_ON_ERROR = 'RUN_PARSE_COMPLETE_ON_ERROR';

// live preview actions
export const LP_START = 'LP_START';
export const LP_END = 'LP_END';
